spring:
  application:
    name: t1-java-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/t1_demo?reWriteBatchedInserts=true
    username: postgres
    password: "0000"
    hikari:
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 5
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 100

  task:
    execution:
      thread-name-prefix: async-task-
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 100
  kafka:
    bootstrap-servers: localhost:9091
    client-id: t1-demo-id
    admin:
      auto-create: false
    producer:
      client-id: t1-demo-producer
      retries: 3
    consumer:
      client-id: t1-demo-consumer
      group-id: t1-demo
      max-poll-records: 100
      enable-auto-commit: false
      auto-offset-reset: earliest

logging:
  level:
    ROOT: INFO
    ru.t1.java.demo.controller.ClientController: TRACE

t1:
  scan-path: ru.t1.java.demo
  kafka:
    producer:
      enable: true
    topic:
      client_registration: t1_demo_client_registration
      client_id_registered: t1_demo_client_registered
      client_transactions: t1_demo_client_transactions
      t1_demo_accounts: t1_demo_accounts
      t1_demo_transactions: t1_demo_transactions
      t1_demo_metric_trace: t1_demo_metric_trace
  aop:
    time-limit-logging:
      logger:
        threshold-millis: 100
      db:
        threshold-millis: 5000
      kafka:
        threshold-millis: 200
