spring:
  application:
    name: t1-java-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/t1_demo?reWriteBatchedInserts=true
    username: postgres
    password: "0000"
    hikari:
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 5
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 100

logging:
  level:
    ROOT: INFO
    ru.t1.java.demo.controller.ClientController: TRACE

t1:
  scan-path: ru.t1.java.demo

t1-aop:
  time-limit-logging:
    logger:
      threshold-millis: 100
    db:
      threshold-millis: 2000
